version: "3.9"

services:
  postgis:
    container_name: postgis-tertiary
    image: postgis/postgis:15-3.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: business
    volumes:
      - "$PWD/pg-data:/var/lib/postgresql/data"
volumes:
  pg_data: { }
